# Generated by Django 4.2.3 on 2023-07-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('type', models.CharField(choices=[('Металл', 'Металл'), ('Пластик', 'Пластик'), ('Техника', 'Техника'), ('Батарейки', 'Батарейки')], default='Металл', max_length=80, verbose_name='Тип')),
                ('weight', models.FloatField(verbose_name='Вес (примерный в кг)')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес, откуда забрать')),
                ('number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('time_s', models.TimeField(verbose_name='Присутствую с')),
                ('time_b', models.TimeField(verbose_name='До')),
                ('is_complited', models.BooleanField(default=False, verbose_name='Заявка выполнена?')),
                ('submitted', models.DateTimeField(auto_now_add=True, verbose_name='Заявка оставлена')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-submitted', 'author'],
            },
        ),
    ]
