# Generated by Django 4.2.3 on 2023-07-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Последний код подтверждения'),
        ),
    ]
